### ISSUE TITLE
License/attribution info

### ISSUE THREAD

**Issue by Xorlent** [erik-de-bont/debontonline#1]
Hi Erik,
     I would like to adapt some of your MSGraph API PS examples to create an O365 monitoring tool and would like to know:

1. If it is permissible to copy your App Registration and Cert signing PowerShell code.
2. What attribution and/or license is required so I can ensure the repo I create adheres to your requirements.

Thanks in advance!

**Comment by erik-de-bont** [comment]
Hi Xorlent,

I have licensed the code under the MIT License, so you can use it accordingly.

Kind Regards,

Erik de Bont
________________________________
From: Xorlent ***@***.***>
Sent: Sunday, November 26, 2023 03:19
To: erik-de-bont/debontonline ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [erik-de-bont/debontonline] License/attribution info (Issue #1)


Hi Erik,
I would like to adapt some of your MSGraph API PS examples to create an O365 monitoring tool and would like to know:

  1.  If it is permissible to copy your App Registration and Cert signing PowerShell code.
  2.  What attribution and/or license is required so I can ensure the repo I create adheres to your requirements.

Thanks in advance!

**Comment by Xorlent** [comment]
Thank you Erik!
